build failure due to
java.lang.NoSuchMethodException: org.apache.maven.surefire.Surefire.run(java.util.List, java.util.List, java.lang.ClassLoader, java.lang.ClassLoader, java.lang.Boolean)
	at java.lang.Class.getMethod(Class.java:1605)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:339)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)